export  const initCars = [
  {id:1, brand: "Volkswagen", model: "Polo", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:2, brand: "Volkswagen", model: "Passat B8", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 4200, class: "business"},
  {id:3, brand: "Skoda", model: "Rapid", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:4, brand: "Nissan", model: "Quashqai", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "144",seats: "экокожа", photo:"", price: 3500, class: "comfort"},
  {id:5, brand: "Renault", model: "Arkana", body: "crossover", year:2022, engine: "2 ", gear: "Автомат", power: "184",seats: "кожа", photo:"", price: 3500, class: "econom"},
  {id:6, brand: "Renault", model: "Kaptur", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 2900, class: "econom"},
  {id:7, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:8, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
  {id:9, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:10, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
  {id:11, brand: "Volkswagen", model: "Polo", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:12, brand: "Volkswagen", model: "Passat B8", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 4200, class: "business"},
  {id:13, brand: "Skoda", model: "Rapid", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:14, brand: "Nissan", model: "Quashqai", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "144",seats: "экокожа", photo:"", price: 3500, class: "comfort"},
  {id:15, brand: "Renault", model: "Arkana", body: "crossover", year:2022, engine: "2 ", gear: "Автомат", power: "184",seats: "кожа", photo:"", price: 3500, class: "econom"},
  {id:16, brand: "Renault", model: "Kaptur", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 2900, class: "econom"},
  {id:17, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:18, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
  {id:19, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:20, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
  {id:21, brand: "Volkswagen", model: "Polo", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:22, brand: "Volkswagen", model: "Passat B8", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 4200, class: "business"},
  {id:23, brand: "Skoda", model: "Rapid", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:24, brand: "Nissan", model: "Quashqai", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "144",seats: "экокожа", photo:"", price: 3500, class: "comfort"},
  {id:25, brand: "Renault", model: "Arkana", body: "crossover", year:2022, engine: "2 ", gear: "Автомат", power: "184",seats: "кожа", photo:"", price: 3500, class: "econom"},
  {id:26, brand: "Renault", model: "Kaptur", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 2900, class: "econom"},
  {id:27, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:28, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
  {id:29, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:30, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
  {id:31, brand: "Volkswagen", model: "Polo", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:32, brand: "Volkswagen", model: "Passat B8", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 4200, class: "business"},
  {id:33, brand: "Skoda", model: "Rapid", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:34, brand: "Nissan", model: "Quashqai", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "144",seats: "экокожа", photo:"", price: 3500, class: "comfort"},
  {id:35, brand: "Renault", model: "Arkana", body: "crossover", year:2022, engine: "2 ", gear: "Автомат", power: "184",seats: "кожа", photo:"", price: 3500, class: "econom"},
  {id:36, brand: "Renault", model: "Kaptur", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 2900, class: "econom"},
  {id:37, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:38, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
  {id:39, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:40, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
  {id:41, brand: "Volkswagen", model: "Polo", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:42, brand: "Volkswagen", model: "Passat B8", body: "sedan", year:2018, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 4200, class: "business"},
  {id:43, brand: "Skoda", model: "Rapid", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "110", seats: "ткань", photo:"", price: 2500, class: "econom"},
  {id:44, brand: "Nissan", model: "Quashqai", body: "sedan", year:2020, engine: "1,6 ", gear: "Автомат", power: "144",seats: "экокожа", photo:"", price: 3500, class: "comfort"},
  {id:45, brand: "Renault", model: "Arkana", body: "crossover", year:2022, engine: "2 ", gear: "Автомат", power: "184",seats: "кожа", photo:"", price: 3500, class: "econom"},
  {id:46, brand: "Renault", model: "Kaptur", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 2900, class: "econom"},
  {id:47, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:48, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
  {id:49, brand: "Toyota", model: "Camry V55", body: "crossover", year:2021, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 8500, class: "business"},
  {id:50, brand: "Audi", model: "A3", body: "crossover", year:2019, engine: "2 ", gear: "Автомат", power: "150",seats: "кожа",photo:"", price: 3500, class: "comfort"},
]
