const ACTypes = {
  LOADING: "LOADING",
  LOADED: "LOADED",

  ERROR: 'ERROR',

  SET_USER: 'SET_USER',
  LOGIN: 'LOGIN',
  LOGUP: 'LOGUP',
  LOGOUT: 'LOGOUT',

  BRAND_FILTER: 'BRAND_FILTER',
  BODY_FILTER: 'BODY_FILTER',
  CLASS_FILTER: 'CLASS_FILTER',
  PRICE_FILTER : 'PRICE_FILTER'
  
};

export const UTypes = {
  EDIT_USER: "EDIT_USER",
  GETBOOKINGS_USER: 'GETBOOKINGS_USER',
};

export default ACTypes;
