const ACTypes = {
  LOADING: "LOADING",
  LOADED: "LOADED",

  ERROR: 'ERROR',

  SET_USER: 'SET_USER',
  LOGIN: 'LOGIN',
  LOGUP: 'LOGUP',
  LOGOUT: 'LOGOUT',

  SET_CARS: 'SET_CARS',

  BRAND_FILTER: 'BRAND_FILTER',
  BODY_FILTER: 'BODY_FILTER',
  CLASS_FILTER: 'CLASS_FILTER',
  PRICE_FILTER : 'PRICE_FILTER',
  FILTER:'FILTER',

  PAGINATE: 'PAGINATE'
  
};
export const UTypes = {
  EDIT_USER: "EDIT_USER",
  GETBOOKINGS_USER: 'GETBOOKINGS_USER',
  GETUSER_USER: 'GETUSER_USER',
  REGISTRATION_USER: 'REGISTRATION_USER',
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  EDIT_AVATAR: 'EDIT_AVATAR',
  ERROR: 'ERROR',
  SET_LOADING: 'SET_LOADING',
  GETMESSAGES_USER: 'GETMESSAGES_USER',
  
};

export default ACTypes;
