const ACTypes = {
  LOADING: "LOADING",
  LOADED: "LOADED",

  ERROR: 'ERROR',

  SET_USER: 'SET_USER',
  LOGIN: 'LOGIN',
  LOGUP: 'LOGUP',
  LOGOUT: 'LOGOUT',

  FILTER: 'FILTER',
  SET_FILTER: 'SET_FILTER'
};

export const UTypes = {
  EDIT_USER: "EDIT_USER",
  GETBOOKINGS_USER: 'GETBOOKINGS_USER',
  LOGIN_USER: 'LOGIN_USER',
  REGISTRATION_USER: 'REGISTRATION_USER',
};

export default ACTypes;
